In [31]:
import pandas as pd

In [32]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], columns=["A", "B", "C"]
                #   , index=["x", "y", "z"]
                  )

In [33]:
df

    A   B   C
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [34]:
# df.columns = ["D", "E", "F"]
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [35]:
df
df.describe()

               A          B          C
count   4.000000   4.000000   4.000000
mean    5.500000   6.500000   7.500000
std     3.872983   3.872983   3.872983
min     1.000000   2.000000   3.000000
25%     3.250000   4.250000   5.250000
50%     5.500000   6.500000   7.500000
75%     7.750000   8.750000   9.750000
max    10.000000  11.000000  12.000000

In [36]:
df

    A   B   C
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [37]:
df.size

12

In [38]:
df.shape

(4, 3)

In [39]:
df.nunique()

A    4
B    4
C    4
dtype: int64

In [40]:
df["A"].unique()

array([ 1,  4,  7, 10])

In [41]:
df["A"].nunique()

4

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   C       4 non-null      int64
dtypes: int64(3)
memory usage: 224.0 bytes

In [43]:
coffee = pd.read_csv("./data/coffee.csv")
# coffee = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv")
# pd.read_excel()
# pd.read_parquet()
# pd.read_feather()
coffee.to_csv("./data/generated/my_coffee.csv", index=False)
coffee.to_parquet("./data/generated/my_coffee.parquet")
coffee.to_feather("./data/generated/my_coffee.feather")
coffee.to_excel("./data/generated/my_coffee.xlsx", index=False)

In [44]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [45]:
coffee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          14 non-null     object
 1   Coffee Type  14 non-null     object
 2   Units Sold   14 non-null     int64
dtypes: int64(1), object(2)
memory usage: 464.0+ bytes

In [46]:
parquet_coffee = pd.read_parquet("./data/generated/my_coffee.parquet")
parquet_coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35